scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 2s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['otel-collector:8889']
#      - targets: ['otel-collector:9999']
